name: auto_generate_jsx

on: [push]

jobs:
  auto_generate_jsx:
    runs-on: ubuntu-latest
    name: auto_generate_jsx
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: genre_check
        id: check
        uses: ugis70194/genre_check@main
        with: 
          target_directory: 'contents'
          target_jsonc: 'detail.jsonc'
      - name: generate
        id: generete
        uses: ugis70194/autoGenerateTSX@main
        with: 
          contents_directory: 'contents'
          target_jsonc: 'detail.jsonc'
          components_directory: 'generated_components'
